### PR TITLE
Separate decode/encode modules

### PR DESCRIPTION
**Pull request by geek**

### CODE REVIEW

**Comment by hueniverse** [comment]
Why?!

**Comment by geek** [comment]
@hueniverse I find it easier to reason about when you separate two.

**Comment by hueniverse** [comment]
This code is done. You really expect to spend time here?

**Comment by geek** [comment]
@hueniverse good point.  I hope that I don't have to.  The only update I plan after this is to document the API.  Hey, one nice benefit (other than simpler to read) will be if you only care about the encoder or decoder, you can include only that part :)

**Comment by cjihrig** [comment]
LGTM @geek

**Pull request merged**
